# Generated by Django 2.1.5 on 2019-08-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190822_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clients',
            field=models.ManyToManyField(related_name='users', to='api.Client'),
        ),
    ]
