# Generated by Django 2.1.5 on 2019-08-26 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190826_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('APPLY_NOW', 'Apply Now'), ('SCHEDULE_A_TOUR', 'Schedule a tour'), ('CONTACT_US', 'Contact Us'), ('JOIN_WAITLIST', 'Join Waitlist')], max_length=16)),
                ('unit_id', models.CharField(max_length=128)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='api.Property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
