# Generated by Django 2.1.5 on 2019-08-27 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_conversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('plan', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('unit', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('LEASED', 'leased'), ('AVAILABLE', 'available'), ('ON_NOTE', 'on_note'), ('REVERSED', 'reserved'), ('OTHER', 'other'), ('LEASED_ON_NOTICE', 'leased_on_notice')], default='AVAILABLE', max_length=16)),
                ('floor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='api.FloorPlan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='property',
            name='resman_account_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='property',
            name='resman_property_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='api.Property'),
        ),
    ]
