# Generated by Django 2.1.5 on 2019-08-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190827_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='propertyLogo/'),
        ),
    ]
