# Generated by Django 2.1.5 on 2019-08-31 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_property_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.CharField(blank=True, max_length=32, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('source', models.CharField(blank=True, max_length=32, null=True)),
                ('origin', models.CharField(blank=True, choices=[('WEB', 'Web'), ('MOBILE', 'Mobile'), ('PHONE', 'Phone'), ('WALK_IN', 'Walk In'), ('UNKNOWN', 'Unknown')], max_length=32, null=True)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('monthly_rent_max', models.FloatField(blank=True, null=True)),
                ('monthly_rent_min', models.FloatField(blank=True, null=True)),
                ('lease_term', models.IntegerField(blank=True, null=True)),
                ('moving_reason', models.CharField(blank=True, choices=[('NEW_JOB', 'New job'), ('CLOSER_TO_FAMILY', 'Close to family'), ('BETTER_LOCATION', 'Better location'), ('OTHER', 'Other')], max_length=32, null=True)),
                ('best_contact_method', models.CharField(blank=True, choices=[('EMAIL', 'Email'), ('PHONE', 'Phone'), ('TEXT', 'Text')], max_length=32, null=True)),
                ('best_contact_time', models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening')], max_length=32, null=True)),
                ('occupants', models.IntegerField(blank=True, null=True)),
                ('beds', models.IntegerField(blank=True, null=True)),
                ('baths', models.IntegerField(blank=True, null=True)),
                ('pets', models.IntegerField(blank=True, null=True)),
                ('pet_type', models.IntegerField(blank=True, choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('BIRD', 'Bird'), ('REPTILE', 'Reptile'), ('FISH', 'Fish'), ('SERVICE_ANIMAL', 'Service Animal')], null=True)),
                ('vehicles', models.IntegerField(blank=True, null=True)),
                ('washer_dryer_method', models.CharField(blank=True, choices=[('IN_UNIT', 'In Unit'), ('HOOK_UP_ONLY', 'Hook up only'), ('ON_PREMISE', 'On premise'), ('NONE', 'None')], max_length=16, null=True)),
                ('stage', models.CharField(blank=True, choices=[('INQUIRY', 'Inquiry'), ('TOUR_SET', 'Tour set'), ('TOUR_COMPLETED', 'Tour completed'), ('APPLICATION_PENDING', 'Application pending'), ('APPLICATION_COMPLETE', 'Application complete')], max_length=32, null=True)),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('LOST', 'Lost'), ('DELETED', 'Deleted')], max_length=16, null=True)),
                ('resman_sync_date', models.DateField(blank=True, null=True)),
                ('resman_sync_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], max_length=16, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='api.Property')),
                ('units', models.ManyToManyField(blank=True, null=True, related_name='leads', to='api.Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed')], default='OPEN', max_length=16)),
                ('type', models.CharField(choices=[('CALL', 'Call'), ('EMAIL', 'Email'), ('TODO', 'To-do'), ('TOUR', 'Tour')], max_length=16)),
                ('due_date', models.DateField()),
                ('lead', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='api.Lead')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
