# Generated by Django 2.1.5 on 2019-09-03 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_lead_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadsFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_filters', to='api.Property')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadsFilterItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('compare_field', models.CharField(max_length=32)),
                ('compare_value', models.CharField(max_length=32)),
                ('lead_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_items', to='api.LeadsFilter')),
            ],
        ),
        migrations.AlterField(
            model_name='lead',
            name='resman_sync_status',
            field=models.CharField(blank=True, choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], max_length=16, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='leadsfilteritem',
            unique_together={('lead_filter', 'compare_field')},
        ),
    ]
