# Generated by Django 2.1.5 on 2019-09-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190904_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='pet_type',
            field=models.CharField(blank=True, choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('BIRD', 'Bird'), ('REPTILE', 'Reptile'), ('FISH', 'Fish'), ('SERVICE_ANIMAL', 'Service Animal')], max_length=16, null=True),
        ),
    ]
