# Generated by Django 2.1.5 on 2019-09-07 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190906_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='api.Property'),
        ),
    ]
