# Generated by Django 2.1.5 on 2019-09-09 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_unit_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tour_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='api.Unit'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.Lead'),
        ),
    ]
