# Generated by Django 2.1.5 on 2019-09-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190911_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('LOST', 'Lost'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=16, null=True),
        ),
    ]
