# Generated by Django 2.1.5 on 2019-09-22 04:47

import backend.api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190918_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='logo',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to=backend.api.utils.upload_image_to),
        ),
    ]
