# Generated by Django 2.1.5 on 2019-09-23 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190921_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='floor_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='api.FloorPlan'),
        ),
    ]
