# Generated by Django 2.1.5 on 2019-09-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20190925_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='current_resident',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='unit_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
