# Generated by Django 2.1.5 on 2019-09-26 07:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('subject', models.CharField(max_length=128)),
                ('text', models.TextField(blank=True, max_length=2048, null=True)),
                ('variables', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128), blank=True, null=True, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='property',
            name='shared_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='shared email'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates', to='api.Property'),
        ),
    ]
