# Generated by Django 2.1.5 on 2019-09-27 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_user_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignLeadOwners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('friday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_lead_owners_friday', to=settings.AUTH_USER_MODEL)),
                ('monday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_lead_owners_monday', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(null=True, unique=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_lead_owners', to='api.Property')),
                ('saturday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_lead_owners_saturday', to=settings.AUTH_USER_MODEL)),
                ('sunday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_lead_owners_sunday', to=settings.AUTH_USER_MODEL)),
                ('thursday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_lead_owners_thursday', to=settings.AUTH_USER_MODEL)),
                ('tuesday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_lead_owners_tuesday', to=settings.AUTH_USER_MODEL)),
                ('wednesday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_lead_owners_wednesday', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
