# Generated by Django 2.1.5 on 2019-10-01 18:21

from django.db import migrations, models


def migrate_existing_stage_and_resman_status(apps, *args, **kwargs):
    Lead = apps.get_model('api', 'lead')
    for lead in Lead.objects.filter(resman_sync_status__isnull=True):
        lead.resman_sync_status = 'NOT_STARTED'
        lead.save()
    for lead in Lead.objects.filter(stage__isnull=True):
        lead.stage = 'INQUIRY'
        lead.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20190930_0008'),
    ]

    operations = [
        migrations.RunPython(migrate_existing_stage_and_resman_status),
        migrations.AlterField(
            model_name='lead',
            name='resman_sync_status',
            field=models.CharField(blank=True, choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('NOT_STARTED', 'Not Started')], default='NOT_STARTED', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(blank=True, choices=[('INQUIRY', 'Inquiry'), ('TOUR_SET', 'Tour set'), ('TOUR_COMPLETED', 'Tour completed'), ('APPLICATION_PENDING', 'Application pending'), ('APPLICATION_COMPLETE', 'Application complete')], default='INQUIRY', max_length=32, null=True),
        ),
    ]
