# Generated by Django 2.1.5 on 2019-10-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20191003_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='floor_plan',
        ),
        migrations.AddField(
            model_name='lead',
            name='floor_plan',
            field=models.ManyToManyField(blank=True, null=True, related_name='leads', to='api.FloorPlan'),
        ),
    ]
