# Generated by Django 2.1.5 on 2019-10-08 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20191008_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectLostReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lost_reason', to='api.Property')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='lead',
            name='resman_event_id',
        ),
        migrations.AddField(
            model_name='lead',
            name='resman_prospect_lost',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='moving_reason',
            field=models.CharField(blank=True, choices=[('EMPLOYMENT', 'Employment'), ('FAMILY', 'Family'), ('OTHER', 'Other')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='api.ProspectLostReason'),
        ),
    ]
