# Generated by Django 2.1.5 on 2019-10-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20191009_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='monthly_rent_max',
            new_name='desired_rent',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='monthly_rent_min',
        ),
    ]
