# Generated by Django 2.1.5 on 2019-10-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20191009_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='pet_type',
            field=models.CharField(blank=True, choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('BIRD', 'Bird')], max_length=16, null=True),
        ),
    ]
