# Generated by Django 2.1.5 on 2019-10-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20191010_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='first_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('property', 'resman_prospect_id')},
        ),
    ]
