# Generated by Django 2.1.5 on 2019-10-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('NOT_AVAILABLE', 'Not Available')], default='AVAILABLE', max_length=16),
        ),
    ]
