# Generated by Django 2.1.5 on 2019-10-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20191026_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_team_account',
            field=models.BooleanField(default=True),
        ),
    ]
