# Generated by Django 2.1.5 on 2019-11-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20191031_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='nylas_status',
            field=models.CharField(blank=True, choices=[('READY_TO_CONNECT', 'Ready to connect'), ('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('AUTH_REQUIRED', 'Auth Required')], max_length=16),
        ),
    ]
