# Generated by Django 2.1.5 on 2019-11-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20191113_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsfilter',
            name='is_display',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='sent_email_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('NEW_LEAD', 'New Lead'), ('NEW_TASK', 'New Task'), ('OVERDUE_TASK', 'Overdue Task'), ('TASK_DUE_TODAY', 'Task due today'), ('TEAM_MENTION', 'Team Mention'), ('EMAIL_BLAST_COMPLETED', 'Email blast completed')], max_length=32),
        ),
    ]
