# Generated by Django 2.1.5 on 2019-11-13 14:43

import django.contrib.postgres.fields
from django.db import migrations, models


def migrate_existing_compare_value(apps, *args, **kwargs):
    LeadsFilterItem = apps.get_model('api', 'LeadsFilterItem')
    for filter_item in LeadsFilterItem.objects.all():
        filter_item.compare_value = [filter_item.compare_value_tmp] if filter_item.compare_value_tmp else []
        filter_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20191113_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsfilteritem',
            name='compare_value',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=None,
                                                            default=list),
        ),
        migrations.RunPython(migrate_existing_compare_value),
    ]
