# Generated by Django 2.1.5 on 2019-11-18 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_remove_leadsfilteritem_compare_value_tmp'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProperty',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('domain', models.CharField(db_index=True, max_length=128)),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('resman_property_id', models.CharField(blank=True, max_length=128)),
                ('resman_account_id', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=16)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('town', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('shared_email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='shared email')),
                ('logo', models.TextField(blank=True, max_length=256, null=True)),
                ('nylas_access_token', models.CharField(blank=True, max_length=255)),
                ('nylas_account_id', models.CharField(blank=True, max_length=255)),
                ('nylas_status', models.CharField(blank=True, choices=[('READY_TO_CONNECT', 'Ready to connect'), ('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('AUTH_REQUIRED', 'Auth Required')], max_length=16)),
                ('nylas_sync_option', models.CharField(choices=[('SYNC_ALL', 'Sync all'), ('SYNC_LABELED', 'Sync labeled')], default='SYNC_ALL', max_length=16)),
                ('sent_email_count', models.IntegerField(default=0)),
                ('is_email_blast_disabled', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Client')),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical property',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
