# Generated by Django 2.1.5 on 2019-11-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_historicalproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='type',
            field=models.CharField(choices=[('TOUR_CONFIRMATION', 'Tour Confirmation'), ('GENERIC', 'Generic'), ('FIRST_FOLLOWUP', 'First Followup'), ('SECOND_FOLLOWUP', 'Second Followup'), ('THIRD_FOLLOWUP', 'Third Followup'), ('FINAL_FOLLOWUP', 'Final Followup'), ('RECEIVED_APPLICATION', 'Received Application')], default='SECOND_FOLLOWUP', max_length=32),
        ),
        migrations.AddField(
            model_name='lead',
            name='confirmation_reminder_async_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='followup_reminder_async_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
