# Generated by Django 2.1.5 on 2019-11-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20191120_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='type',
            field=models.CharField(choices=[('TOUR_CONFIRMATION', 'Tour Confirmation'), ('GENERIC', 'Generic'), ('FIRST_FOLLOWUP', 'First Followup'), ('SECOND_FOLLOWUP', 'Second Followup'), ('THIRD_FOLLOWUP', 'Third Followup'), ('FINAL_FOLLOWUP', 'Final Followup'), ('RECEIVED_APPLICATION', 'Received Application')], default='GENERIC', max_length=32),
        ),
    ]
