# Generated by Django 2.1.5 on 2019-11-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20191121_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together={('property', 'name')},
        ),
    ]
