# Generated by Django 2.1.5 on 2019-11-27 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20191122_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tour_confirmation_reminder_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
