# Generated by Django 2.1.5 on 2019-12-07 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_lead_application_complete_email_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roommate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('relationship', models.CharField(choices=[('SPOUSE', 'Spouse'), ('PARTNER', 'Partner'), ('ROOMMATE', 'Roommate'), ('CHILD', 'Child'), ('GUARANTOR', 'Guarantor')], default='ROOMMATE', max_length=16)),
                ('email', models.EmailField(blank=True, max_length=64, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('resman_person_id', models.CharField(blank=True, max_length=64, null=True)),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roommates', to='api.Lead')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roommates', to='api.Property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
