# Generated by Django 2.1.5 on 2019-12-11 08:33

import django.contrib.postgres.fields
from django.db import migrations, models


def migrate_existing_days_to_move_in(apps, *args, **kwargs):
    Lead = apps.get_model('api', 'Lead')
    for lead in Lead.objects.filter(move_in_date__isnull=False, days_to_move_in__isnull=True):
        lead.days_to_move_in = (lead.move_in_date - lead.created.date()).days
        lead.save()


def migrate_existing_last_followup_date(apps, *args, **kwargs):
    Lead = apps.get_model('api', 'Lead')
    EmailMessage = apps.get_model('api', 'EmailMessage')
    for lead in Lead.objects.filter(last_followup_date__isnull=True):
        last_followup = EmailMessage.objects.filter(lead=lead.pk, receiver_email=lead.email).order('-date').first()
        lead.last_followup_date = last_followup.date if last_followup else None
        lead.save()


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0064_auto_20191208_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='days_to_move_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_followup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadsfilteritem',
            name='compare_value',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32),
                                                            default=list, size=None),
        ),
        migrations.RunPython(migrate_existing_days_to_move_in, migrate_existing_last_followup_date),
    ]
