# Generated by Django 2.1.5 on 2019-12-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20191211_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('MARK_TAYLOR', 'Mark Taylor'), ('ASSET_MANAGER', 'Asset Manager'), ('SUBMARKET', 'Submarket')], max_length=32)),
                ('properties', models.ManyToManyField(related_name='portfolios', to='api.Property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
