# Generated by Django 2.1.5 on 2020-01-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='closed_status_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
