# Generated by Django 2.1.5 on 2020-01-15 11:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_lead_closed_status_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectsource',
            name='spends',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
