# Generated by Django 2.1.5 on 2020-01-22 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20200116_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=64)),
                ('attachment', models.FileField(upload_to='')),
                ('name', models.CharField(default='attachment', max_length=255)),
                ('size', models.IntegerField(default=0)),
                ('content_type', models.CharField(default='image/jpeg', max_length=255)),
                ('email_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.EmailMessage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
