# Generated by Django 2.1.5 on 2020-01-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_emailattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailattachment',
            name='name',
            field=models.CharField(blank=True, default='attachment', max_length=255, null=True),
        ),
    ]
