# Generated by Django 2.1.5 on 2020-02-06 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20200203_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_source_leads', to='api.ProspectSource'),
        ),
    ]
