# Generated by Django 2.1.5 on 2020-02-09 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_lead_last_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=64)),
                ('prospect_phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('answered_status', models.BooleanField(default=True)),
                ('duration', models.IntegerField(default=0)),
                ('recording', models.FileField(blank=True, null=True, upload_to='call_recording')),
                ('call_id', models.CharField(blank=True, max_length=32, null=True)),
                ('transcription', models.TextField(blank=True, null=True)),
                ('is_transcribed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='api.Lead')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='api.Property')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='call',
            unique_together={('property', 'call_id')},
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_released',
            field=models.BooleanField(default=False),
        )
    ]
