# Generated by Django 2.1.5 on 2020-03-05 03:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_auto_20200226_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator('\\d+')]),
        ),
    ]
