# Generated by Django 2.1.5 on 2020-03-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_auto_20200305_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproperty',
            name='nylas_status',
            field=models.CharField(blank=True, choices=[('READY_TO_CONNECT', 'Ready to connect'), ('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('AUTH_REQUIRED', 'Auth Required'), ('SYNCING', 'Syncing')], max_length=16),
        ),
        migrations.AlterField(
            model_name='property',
            name='nylas_status',
            field=models.CharField(blank=True, choices=[('READY_TO_CONNECT', 'Ready to connect'), ('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('AUTH_REQUIRED', 'Auth Required'), ('SYNCING', 'Syncing')], max_length=16),
        ),
    ]
