# Generated by Django 2.1.5 on 2020-03-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_auto_20200307_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproperty',
            name='nylas_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='nylas_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='nylas_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='nylas_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
