# Generated by Django 2.1.5 on 2020-03-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_auto_20200309_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lost_status_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='tour_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
