# Generated by Django 2.2.10 on 2020-03-22 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_auto_20200317_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='partly_owned_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partial_owner', to='api.Property'),
        ),
    ]
