# Generated by Django 2.2.10 on 2020-03-25 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_ilsemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_default_filter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lead_default_filter',
            field=models.CharField(blank=True, default='all_leads', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='lead_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.LeadsFilter'),
        ),
    ]
