# Generated by Django 2.2.10 on 2020-03-26 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_auto_20200325_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilsemail',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ils_emails', to='api.Lead'),
        ),
    ]
