# Generated by Django 2.2.10 on 2020-03-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_ilsemail_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_follow_up',
            field=models.BooleanField(default=False),
        ),
    ]
