# Generated by Django 2.2.10 on 2020-03-26 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_note_is_follow_up'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='days_to_move_in',
        ),
    ]
