# Generated by Django 2.1.5 on 2020-03-26 07:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_remove_lead_days_to_move_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='lead_response_time',
            new_name='lead_response_time_business',
        ),
        migrations.AddField(
            model_name='report',
            name='lead_response_time_non_business',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), blank=True,
                                                            null=True, size=None),
        ),
        migrations.RemoveField(
            model_name='report',
            name='followups_24_hours',
        ),
        migrations.RemoveField(
            model_name='report',
            name='followups_2_hours',
        ),
        migrations.RemoveField(
            model_name='report',
            name='followups_48_hours',
        ),
        migrations.RemoveField(
            model_name='report',
            name='followups_more_48_hours',
        ),
        migrations.AddField(
            model_name='report',
            name='followups_24_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True,
                                                            null=True, size=None),
        ),
        migrations.AddField(
            model_name='report',
            name='followups_2_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True,
                                                            null=True, size=None),
        ),
        migrations.AddField(
            model_name='report',
            name='followups_48_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True,
                                                            null=True, size=None),
        ),
        migrations.AddField(
            model_name='report',
            name='followups_more_48_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True,
                                                            null=True, size=None),
        ),
    ]
