# Generated by Django 2.1.5 on 2020-03-26 07:56

from django.db import migrations


def migrate_lead_columns(apps, *args, **kwargs):
    Column = apps.get_model('api', 'Column')
    Property = apps.get_model('api', 'Property')
    for property in Property.objects.all():
        last_column = Column.objects.filter(property=property).order_by('-position').first()
        if not last_column:
            continue
        last_position = last_column.position
        # Most case, created field will be the last position, so we'd insert new field before it.
        last_column.position = last_position + 1
        last_column.save()
        Column.objects.create(name='last_activity_date', position=last_position, property=property)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_auto_20200326_0756'),
    ]

    operations = [
        migrations.RunPython(migrate_lead_columns),
    ]
