# Generated by Django 2.2.10 on 2020-03-29 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_migrate_lead_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_default_filter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lead_default_filter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lead_filter',
        ),
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(blank=True, choices=[('INQUIRY', 'Inquiry'), ('CONTACT_MADE', 'Contact mode'), ('TOUR_SET', 'Tour set'), ('TOUR_COMPLETED', 'Tour completed'), ('WAITLIST', 'Waitlist'), ('APPLICATION_PENDING', 'Application pending'), ('APPLICATION_COMPLETE', 'Application complete')], default='INQUIRY', max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='ActiveLeadsFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lead_default_filter', models.CharField(blank=True, default='all_leads', max_length=32)),
                ('is_default_filter', models.BooleanField(default=True)),
                ('lead_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.LeadsFilter')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_leads_filter', to='api.Property')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_leads_filter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
