# Generated by Django 2.2.10 on 2020-03-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_auto_20200329_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_activity_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
