# Generated by Django 2.2.10 on 2020-03-30 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_lead_last_activity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.Lead'),
        ),
    ]
