# Generated by Django 2.2.10 on 2020-04-01 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_user_has_advanced_reports_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='api.Lead'),
        ),
        migrations.AlterUniqueTogether(
            name='leadsfilter',
            unique_together={('name', 'property')},
        ),
    ]
