# Generated by Django 2.2.10 on 2020-04-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_auto_20200402_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='resman_sync_status',
            field=models.CharField(blank=True, choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('NOT_STARTED', 'Not Started'), ('SYNCING', 'Syncing')], default='NOT_STARTED', max_length=16, null=True),
        ),
    ]
