# Generated by Django 2.2.10 on 2020-03-31 08:10

from django.db import migrations, models


def migrate_update_activity_content(apps, *args, **kwargs):
    Activity = apps.get_model('api', 'Activity')
    Activity.objects.filter(content='Status updated to Closed').update(content='Status updated to Leased')


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0104_auto_20200412_1205'),
    ]

    operations = [
        migrations.RunPython(migrate_update_activity_content),
    ]
