# Generated by Django 2.2.11 on 2020-04-21 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_auto_20200417_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='call',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='api.Lead'),
        ),
    ]
