# Generated by Django 2.2.11 on 2020-05-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_auto_20200508_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='new_type',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='old_title',
        ),
        migrations.AlterField(
            model_name='task',
            name='old_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.RenameField(
            model_name='task',
            old_name='type',
            new_name='old_type',
        ),
        migrations.AlterField(
            model_name='task',
            name='old_type',
            field=models.CharField(blank=True,
                                   choices=[('CALL', 'Call'), ('EMAIL', 'Email'), ('TODO', 'To-do'), ('TOUR', 'Tour')],
                                   max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('FIRST_FOLLOWUP', 'First Follow-up'), ('SECOND_FOLLOWUP', 'Second Follow-up'), ('THIRD_FOLLOWUP', 'Third Follow-up'), ('FINAL_FOLLOWUP', 'Final Follow-up'), ('FUTURE_DATE_FOLLOWUP', 'Future Date Follow-up'), ('CHECK_APP', 'Check for Application'), ('CHECK_DOCS', 'Check for Documents'), ('PRICE_AVAILABILITY', 'Send New Price/Availability'), ('TOUR', 'Schedule Tour'), ('VIRTUAL_TOUR', 'Schedule Virtual Tour')], default='FIRST_FOLLOWUP', max_length=32),
        ),
    ]
