# Generated by Django 2.2.11 on 2020-05-12 01:20

from django.db import migrations
from difflib import get_close_matches


def migrate_existing_task_titles(apps, schema_editor):
    Task = apps.get_model('api', 'Task')
    task_choices = {'first follow_up': 'FIRST_FOLLOWUP', 'second follow_up': 'SECOND_FOLLOWUP', 'third follow_up': 'THIRD_FOLLOWUP',
                    'final follow_up': 'FINAL_FOLLOWUP', 'future date follow_up': 'FUTURE_DATE_FOLLOWUP',
                    'check for application': 'CHECK_APP', 'check for documents': 'CHECK_DOCS',
                    'send new price/availability': 'PRICE_AVAILABILITY', 'schedule tour': 'TOUR',
                    'schedule virtual tour': 'VIRTUAL_TOUR', }
    for task in Task.objects.exclude(old_title=None):
        title = task.old_title.lower().replace('2', 'second').replace('3', 'third')
        if title == 'follow-up' or title == 'follow up':
            task.type = 'FIRST_FOLLOWUP'
            task.save()
            continue
        match = get_close_matches(title, task_choices.keys(), n=1)
        if len(match) > 0:
            task.type = task_choices[match[0]]
            task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_auto_20200512_0920'),
    ]

    operations = [
        migrations.RunPython(migrate_existing_task_titles),
    ]
