# Generated by Django 2.2.10 on 2020-05-25 08:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_auto_20200525_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0)),
                ('start_time', models.TimeField(blank=True, default=datetime.datetime(2020, 5, 25, 16, 0, tzinfo=utc), null=True)),
                ('end_time', models.TimeField(blank=True, default=datetime.datetime(2020, 5, 26, 0, 30, tzinfo=utc), null=True)),
                ('is_workday', models.BooleanField(default=True)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='api.Property')),
            ],
            options={
                'unique_together': {('property', 'weekday')},
            },
        ),
    ]
