# Generated by Django 2.2.11 on 2020-05-12 17:47

from django.db import migrations, models
import django.db.models.deletion


def migrate_existing_call_isLH(apps, schema_editor):
    Call = apps.get_model('api', 'Call')
    for call in Call.objects.all():
        call.is_LH = True
        call.save()


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0118_historicalbusinesshours'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='call_category',
            field=models.CharField(choices=[('PROSPECT', 'Prospect'), ('NON PROSPECT', 'Non Prospect')],
                                   default='PROSPECT', max_length=16),
        ),
        migrations.AddField(
            model_name='call',
            name='call_result',
            field=models.CharField(
                choices=[('connected', 'Connected'), ('no-answer', 'No Answer'), ('busy', 'Busy'), ('failed', 'Failed'),
                         ('queued', 'Queued'), ('ringing', 'Ringing'), ('in-progress', 'In Progress'),
                         ('completed', 'Completed')], default='completed', max_length=16),
        ),
        migrations.AddField(
            model_name='call',
            name='call_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='is_LH',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='call',
            name='recording_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='target_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='call_busy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='call_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='source',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='Property Target Number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='Property Target Number'),
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('type', models.CharField(choices=[('SMS', 'SMS'), ('TRACKING', 'Tracking')], default='TRACKING',
                                          max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('twilio_sid', models.CharField(blank=True, max_length=64, null=True)),
                ('property',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers',
                                   to='api.Property')),
                ('source',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers',
                                   to='api.ProspectSource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(migrate_existing_call_isLH),
    ]
