# Generated by Django 2.2.11 on 2020-05-14 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_auto_20200526_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='call_busy',
        ),
        migrations.RemoveField(
            model_name='report',
            name='call_failed',
        ),
    ]
