# Generated by Django 2.2.11 on 2020-05-19 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_auto_20200527_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_message_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SMSContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered'), ('undelivered', 'Un Delivered'), ('receiving', 'Receiving'), ('received', 'Received'), ('read', 'Read')], default='queued', max_length=16)),
                ('message', models.TextField()),
                ('sender_number', models.CharField(blank=True, max_length=32, null=True)),
                ('reciever_number', models.CharField(blank=True, max_length=32, null=True)),
                ('is_team_message', models.BooleanField(default=False)),
                ('twilio_sid', models.CharField(blank=True, max_length=64, null=True)),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms', to='api.Lead')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms', to='api.Property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
