# Generated by Django 2.2.10 on 2020-05-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_auto_20200527_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='call_busy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='call_failed',
            field=models.IntegerField(default=0),
        ),
    ]
