# Generated by Django 2.2.11 on 2020-05-29 03:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_auto_20200528_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smscontent',
            old_name='reciever_number',
            new_name='receiver_number',
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 5, 30, 0, 30, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 5, 29, 16, 0, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='historicalbusinesshours',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 5, 30, 0, 30, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='historicalbusinesshours',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 5, 29, 16, 0, tzinfo=utc), null=True),
        ),
    ]
