# Generated by Django 2.2.11 on 2020-05-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_auto_20200529_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='is_LH',
        ),
        migrations.AddField(
            model_name='smscontent',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
