# Generated by Django 2.2.11 on 2020-06-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_auto_20200601_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smscontent',
            name='is_team_message',
        ),
        migrations.AddField(
            model_name='lead',
            name='last_message_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='smscontent',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('NEW_LEAD', 'New Lead'), ('NEW_TASK', 'New Task'), ('OVERDUE_TASK', 'Overdue Task'), ('TASK_DUE_TODAY', 'Task due today'), ('TEAM_MENTION', 'Team Mention'), ('EMAIL_BLAST_COMPLETED', 'Email blast completed'), ('NEW_CALL', 'New call recording'), ('NEW_SMS', 'New incoming SMS')], max_length=32),
        ),
    ]
