# Generated by Django 2.2.11 on 2020-06-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_auto_20200604_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproperty',
            name='is_using_resman',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_using_resman',
            field=models.BooleanField(default=True),
        ),
    ]
