# Generated by Django 2.2.11 on 2020-06-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0130_auto_20200605_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
