# Generated by Django 2.2.10 on 2020-06-15 13:29

from django.db import migrations, models


def migrate_source_names(apps, schema_editor):
    ProspectSource = apps.get_model('api', 'ProspectSource')
    SourceMatching = apps.get_model('api', 'SourceMatching')
    source_names = ProspectSource.objects.distinct('name').values('name')
    for name in source_names:
        SourceMatching.objects.create(LH_source=name.get('name'), ResMan_source=name.get('name'))


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0131_auto_20200612_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceMatching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('LH_source', models.CharField(max_length=128)),
                ('ResMan_source', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(migrate_source_names),
    ]
