# Generated by Django 2.2.10 on 2020-06-15 13:29

from django.db import migrations, models


def migrate_call_missed_status(apps, schema_editor):
    Call = apps.get_model('api', 'Call')
    Call.objects.filter(answered_status=False).update(call_result='no-answer')


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0132_sourcematching'),
    ]

    operations = [
        migrations.RunPython(migrate_call_missed_status),
    ]
