# Generated by Django 2.2.10 on 2020-06-17 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0133_migrate_call_missed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source_lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_leads', to='api.Lead'),
        ),
        migrations.AddField(
            model_name='note',
            name='has_shared_lead_link',
            field=models.BooleanField(default=False),
        ),
    ]
