# Generated by Django 2.2.11 on 2020-07-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0136_auto_20200701_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallead',
            name='stage',
            field=models.CharField(blank=True, choices=[('INQUIRY', 'Inquiry'), ('CONTACT_MADE', 'Contact made'), ('TOUR_SET', 'Tour set'), ('TOUR_COMPLETED', 'Tour completed'), ('WAITLIST', 'Waitlist'), ('APPLICATION_PENDING', 'Application pending'), ('APPLICATION_COMPLETE', 'Application complete')], default='INQUIRY', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(blank=True, choices=[('INQUIRY', 'Inquiry'), ('CONTACT_MADE', 'Contact made'), ('TOUR_SET', 'Tour set'), ('TOUR_COMPLETED', 'Tour completed'), ('WAITLIST', 'Waitlist'), ('APPLICATION_PENDING', 'Application pending'), ('APPLICATION_COMPLETE', 'Application complete')], default='INQUIRY', max_length=32, null=True),
        ),
    ]
