# Generated by Django 2.2.11 on 2020-07-09 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0137_auto_20200707_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='answered_status',
        ),
    ]
