# Generated by Django 2.2.11 on 2020-07-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0139_auto_20200723_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(blank=True, max_length=32)),
                ('secret_key', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_external_vendor',
        ),
    ]
