# Generated by Django 2.2.11 on 2020-08-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0140_auto_20200729_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorauth',
            name='source',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
