# Generated by Django 2.2.11 on 2020-08-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0141_vendorauth_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorauth',
            name='partner',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
