# Generated by Django 2.2.11 on 2020-08-06 00:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_vendorauth_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='bathrooms',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='bedrooms',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='max_rent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='min_rent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='square_footage',
            field=models.IntegerField(default=0),
        ),
    ]
