# Generated by Django 2.1.5 on 2020-03-26 07:56

from django.db import migrations


def migrate_lead_columns(apps, *args, **kwargs):
    Column = apps.get_model('api', 'Column')
    Property = apps.get_model('api', 'Property')
    for property in Property.objects.all():
        acquisition__column = Column.objects.filter(property=property, name='acquisition_date').first()
        if not property.column.count() or acquisition__column:
            continue
        max_position = Column.objects.filter(property=property).order_by('-position').first().position
        Column.objects.create(name='acquisition_date', position=max_position + 1, property=property)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0143_auto_20200806_0023'),
    ]

    operations = [
        migrations.RunPython(migrate_lead_columns),
    ]
