# Generated by Django 2.2.11 on 2020-08-07 06:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0144_add_acquisition_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallead',
            name='resman_changed_field',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32), default=list, size=None),
        ),
        migrations.AddField(
            model_name='lead',
            name='resman_changed_field',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32), default=list, size=None),
        ),
    ]
