# Generated by Django 2.1.5 on 2020-03-26 07:56

from django.db import migrations


def migrate_lead_columns(apps, *args, **kwargs):
    Column = apps.get_model('api', 'Column')
    Property = apps.get_model('api', 'Property')
    for property in Property.objects.all():
        created_column = Column.objects.filter(property=property, name='created').first()
        acquisition_date_column = Column.objects.filter(property=property, name='acquisition_date').first()
        if not created_column or not acquisition_date_column:
            continue
        tmp = acquisition_date_column.position
        acquisition_date_column.position = created_column.position
        acquisition_date_column.save()
        acquisition_date_column.is_visible = True

        created_column.position = tmp
        created_column.is_visible = False

        acquisition_date_column.save()
        created_column.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0148_auto_20200830_1621'),
    ]

    operations = [
        migrations.RunPython(migrate_lead_columns),
    ]
