# Generated by Django 2.2.11 on 2020-09-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0150_auto_20200911_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='bot_response_state',
            field=models.CharField(blank=True, choices=[('ANSWERED', 'Answered'), ('REPHRASED', 'Rephrased'), ('PROMPT', 'Prompt')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='hobbes_answered_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='hobbes_chat_conversations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='question_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='action',
            field=models.CharField(blank=True, choices=[('VIEW_PHOTOS', 'View photos'), ('SCHEDULE_TOUR', 'Schedule a tour'), ('RESCHEDULE_TOUR', 'Reschedule tour / edit tour'), ('CANCEL_TOUR', 'Cancel tour'), ('CHECK_PRICES', 'Check prices / availability'), ('RESIDENT_ACCESS', 'Resident access'), ('QUESTION', 'I have a question')], max_length=32, null=True),
        ),
    ]
