# Generated by Django 2.2.11 on 2020-09-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0151_auto_20200915_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallead',
            name='baths',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='beds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='baths',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='beds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
