# Generated by Django 2.2.11 on 2020-10-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0152_auto_20200919_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproperty',
            name='mark_taylor_base_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='mark_taylor_base_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
