# Generated by Django 2.2.11 on 2020-10-08 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0153_auto_20201005_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=16, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('is_allowed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReasonForMoving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=16, null=True)),
                ('reason', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=32, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='historicallead',
            old_name='resman_sync_condition_lack_reason',
            new_name='pms_sync_condition_lack_reason',
        ),
        migrations.RenameField(
            model_name='historicallead',
            old_name='resman_sync_date',
            new_name='pms_sync_date',
        ),
        migrations.RenameField(
            model_name='historicallead',
            old_name='resman_sync_status',
            new_name='pms_sync_status',
        ),
        migrations.RenameField(
            model_name='historicalproperty',
            old_name='last_resman_sync_time',
            new_name='last_pms_sync_time',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='resman_sync_condition_lack_reason',
            new_name='pms_sync_condition_lack_reason',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='resman_sync_date',
            new_name='pms_sync_date',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='resman_sync_status',
            new_name='pms_sync_status',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='last_resman_sync_time',
            new_name='last_pms_sync_time',
        ),
        migrations.AddField(
            model_name='floorplan',
            name='external_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='group_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='real_page_customer_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='real_page_guest_card_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='res_man_pet_weight',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='real_page_pmc_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='real_page_site_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='lead',
            name='real_page_customer_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='real_page_guest_card_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='res_man_pet_weight',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='real_page_pmc_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='property',
            name='real_page_site_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='prospectlostreason',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lost_reasons', to='api.Property'),
        ),
        migrations.AddField(
            model_name='roommate',
            name='real_page_customer_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='external_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='prospectlostreason',
            name='external_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),

        migrations.AddField(
            model_name='relationshiptype',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_types', to='api.Property'),
        ),
        migrations.AddField(
            model_name='reasonformoving',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reason_for_moving', to='api.Property'),
        ),
        migrations.CreateModel(
            name='RealPageEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('external_id', models.CharField(blank=True, max_length=128, null=True)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_page_employees', to='api.Property')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_page_employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'RealPage employees',
            },
        ),
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=16, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_ranges', to='api.Property')),
            ],
        ),
        migrations.CreateModel(
            name='PetWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=16, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet_weights', to='api.Property')),
            ],
        ),
        migrations.AddField(
            model_name='pettype',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet_types', to='api.Property'),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='price_range',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.PriceRange'),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='real_page_pet_weight',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.PetWeight'),
        ),
        migrations.AddField(
            model_name='lead',
            name='price_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='api.PriceRange'),
        ),
        migrations.AddField(
            model_name='lead',
            name='real_page_pet_weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='api.PetWeight'),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='moving_reason_link',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='api.ReasonForMoving'),
        ),
        migrations.AddField(
            model_name='lead',
            name='moving_reason_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='leads', to='api.ReasonForMoving'),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='pet_type_link',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='api.PetType'),
        ),
        migrations.AddField(
            model_name='lead',
            name='pet_type_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='leads', to='api.PetType'),
        ),
        migrations.AddField(
            model_name='roommate',
            name='relationship_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roommates',
                                    to='api.RelationshipType'),
        ),
    ]
