# Generated by Django 2.2.13 on 2020-09-24 12:25

from django.db import migrations


def migrate_pet_types(apps, *args, **kwargs):
    Property = apps.get_model('api', 'Property')
    Lead = apps.get_model('api', 'Lead')
    PetType = apps.get_model('api', 'PetType')
    PET_TYPE_CHOICES = (('DOG', 'Dog'), ('CAT', 'Cat'), ('BIRD', 'Bird'),)
    for property in Property.objects.exclude(resman_property_id='').all():
        for name in PET_TYPE_CHOICES:
            pet_type = PetType.objects.create(property=property, name=name[1])
            leads = Lead.objects.filter(property=property, pet_type=name[0])
            leads.update(pet_type_link=pet_type)


def migrate_moving_reasons(apps, *args, **kwargs):
    Property = apps.get_model('api', 'Property')
    Lead = apps.get_model('api', 'Lead')
    ReasonForMoving = apps.get_model('api', 'ReasonForMoving')
    MOVING_REASON_CHOICES = (('EMPLOYMENT', 'Employment'), ('FAMILY', 'Family'), ('OTHER', 'Other'))
    for property in Property.objects.exclude(resman_property_id='').all():
        for name in MOVING_REASON_CHOICES:
            moving_reason = ReasonForMoving.objects.create(property=property, reason=name[1])
            leads = Lead.objects.filter(property=property, moving_reason=name[0])
            leads.update(moving_reason_link=moving_reason)


def migrate_relationship_types(apps, *args, **kwargs):
    Property = apps.get_model('api', 'Property')
    Roommate = apps.get_model('api', 'Roommate')
    RelationshipType = apps.get_model('api', 'RelationshipType')
    RELATIONSHIP_TYPE_CHOICES = (('SPOUSE', 'Spouse'), ('PARTNER', 'Partner'), ('CHILD', 'Child'),
                                 ('ROOMMATE', 'Roommate'), ('GUARANTOR', 'Guarantor'),)
    for property in Property.objects.exclude(resman_property_id='').all():
        for choice in RELATIONSHIP_TYPE_CHOICES:
            relationship_type = RelationshipType.objects.create(property=property, name=choice[1], value=choice[0])
            roommates = Roommate.objects.filter(property=property, relationship=choice[0])
            roommates.update(relationship_link=relationship_type)


def migrate_lost_reasons(apps, *args, **kwargs):
    Property = apps.get_model('api', 'Property')
    Lead = apps.get_model('api', 'Lead')
    ProspectLostReason = apps.get_model('api', 'ProspectLostReason')
    for lost_reason in ProspectLostReason.objects.all():
        external_id = lost_reason.external_id
        lost_reason.external_id = None
        lost_reason.save()
        for property in Property.objects.filter(resman_account_id=lost_reason.account_id):
            new_lost_reason = ProspectLostReason.objects.create(property=property, external_id=external_id,
                                                                name=lost_reason.name)
            leads = Lead.objects.filter(property=property, lost_reason=lost_reason)
            leads.update(lost_reason=new_lost_reason)


def remove_old_lost_reasons(apps, *args, **kwargs):
    ProspectLostReason = apps.get_model('api', 'ProspectLostReason')
    ProspectLostReason.objects.filter(property=None).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0154_auto_20201007_2012'),
    ]

    operations = [
        migrations.RunPython(migrate_pet_types),
        migrations.RunPython(migrate_moving_reasons),
        migrations.RunPython(migrate_relationship_types),
        migrations.RunPython(migrate_lost_reasons),
        migrations.RunPython(remove_old_lost_reasons),
    ]
