# Generated by Django 2.2.11 on 2020-10-08 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0155_migrate_pms_sync_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallead',
            name='moving_reason',
        ),
        migrations.RemoveField(
            model_name='historicallead',
            name='pet_type',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='moving_reason',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='pet_type',
        ),
        migrations.RemoveField(
            model_name='roommate',
            name='relationship',
        ),
        migrations.RemoveField(
            model_name='prospectlostreason',
            name='account_id',
        ),
    ]
