# Generated by Django 2.2.11 on 2020-10-08 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0156_delete_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicallead',
            old_name='moving_reason_link',
            new_name='moving_reason',
        ),
        migrations.RenameField(
            model_name='historicallead',
            old_name='pet_type_link',
            new_name='pet_type',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='moving_reason_link',
            new_name='moving_reason',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='pet_type_link',
            new_name='pet_type',
        ),
        migrations.RenameField(
            model_name='roommate',
            old_name='relationship_link',
            new_name='relationship',
        ),
    ]
