# Generated by Django 2.2.11 on 2020-10-08 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0157_auto_20201007_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_numbers', to='api.ProspectSource'),
        ),
    ]
