# Generated by Django 2.2.13 on 2020-10-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0159_auto_20201014_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproperty',
            old_name='smartrent_group_id',
            new_name='smart_rent_group_id',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='smartrent_group_id',
            new_name='smart_rent_group_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='smartrent_id',
            new_name='smart_rent_id',
        ),
        migrations.RemoveField(
            model_name='chatprospect',
            name='smartrent_id',
        ),
        migrations.AddField(
            model_name='historicallead',
            name='smart_rent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='smart_rent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='smart_rent_unit_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
