# Generated by Django 2.2.13 on 2020-10-15 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0160_auto_20201015_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='resmanemployee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='res_man_employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
