# Generated by Django 2.2.13 on 2020-10-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0161_resmanemployee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='can_be_toured',
            field=models.BooleanField(default=False),
        ),
    ]
