# Generated by Django 2.2.13 on 2020-10-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0164_auto_20201027_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproperty',
            name='mst_property_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='mst property email'),
        ),
        migrations.AddField(
            model_name='property',
            name='mst_property_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='mst property email'),
        ),
    ]
