# Generated by Django 2.2.13 on 2020-11-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0165_auto_20201030_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoredcall',
            name='omitted_questions',
            field=models.ManyToManyField(blank=True, null=True, related_name='omitted_scored_calls', to='api.CallScoringQuestion'),
        ),
    ]
