# Generated by Django 2.2.13 on 2020-11-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0168_auto_20201112_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disable_notification',
            field=models.BooleanField(default=False),
        ),
    ]
