# Generated by Django 2.2.13 on 2020-11-27 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0169_user_disable_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallead',
            name='last_message',
        ),
        migrations.RemoveField(
            model_name='historicallead',
            name='last_message_date',
        ),
        migrations.RemoveField(
            model_name='historicallead',
            name='last_message_read',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_message',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_message_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_message_read',
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='is_shown_in_modal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatprospect',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatprospect',
            name='source',
            field=models.CharField(choices=[('SITE', 'Standalone Website'), ('MT', 'Mark-Taylor')], default='SITE', max_length=24),
        ),
        migrations.AddField(
            model_name='client',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_tmp', to='api.Customer'),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Customer'),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='platform',
            field=models.CharField(choices=[('SITE_ONLY', 'Site Only'), ('DWELL_ONLY', 'Dwell Only'), ('BOTH', 'Site and Dwell')], default='SITE_ONLY', max_length=16),
        ),
        migrations.AddField(
            model_name='property',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties_tmp', to='api.Customer'),
        ),
        migrations.AddField(
            model_name='property',
            name='platform',
            field=models.CharField(choices=[('SITE_ONLY', 'Site Only'), ('DWELL_ONLY', 'Dwell Only'), ('BOTH', 'Site and Dwell')], default='SITE_ONLY', max_length=16),
        ),
        migrations.AddField(
            model_name='scoredcall',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_scored_calls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smscontent',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_contents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='type',
            field=models.CharField(choices=[('AGENT', 'Agent message'), ('BOT', 'Bot message'), ('PROSPECT', 'Prospect message'), ('JOINED', 'Agent joined'), ('AGENT_REQUEST', 'Agent request'), ('GREETING', 'Greeting message'), ('DATA_CAPTURE', 'Data capture element')], default='BOT', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LIFT_LYTICS_ADMIN', 'Lift Lytics Admin'), ('GENERIC_ADMIN', 'Generic Admin'), ('CUSTOMER_ADMIN', 'Customer Admin'), ('PROPERTY_ADMIN', 'Property Admin')], max_length=32),
        ),
    ]
