# Generated by Django 2.2.13 on 2020-11-27 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0171_auto_20201127_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='properties',
        ),
        migrations.AlterField(
            model_name='client',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='api.Customer'),
        ),
        migrations.AlterField(
            model_name='property',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='api.Customer'),
        ),
    ]
