# Generated by Django 2.2.13 on 2020-12-02 08:52

from django.db import migrations


def migrate_customer_admin(apps, schema_editor):
    Customer = apps.get_model('api', 'Customer')
    for customer in Customer.objects.exclude(user=None):
        user = customer.user
        user.customer = customer
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0175_report_agent_chats'),
    ]

    operations = [
        migrations.RunPython(migrate_customer_admin),
    ]
