# Generated by Django 2.2.13 on 2020-12-02 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0176_migrate_customer_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
