# Generated by Django 2.2.13 on 2020-12-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0177_remove_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_super_customer',
            field=models.BooleanField(default=False),
        ),
    ]
