# Generated by Django 2.2.13 on 2020-12-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0178_user_is_super_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_access_to_up_platform',
            field=models.BooleanField(default=False),
        ),
    ]
