# Generated by Django 2.2.13 on 2020-12-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0179_user_has_access_to_up_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LIFT_LYTICS_ADMIN', 'Dwell Admin'), ('GENERIC_ADMIN', 'Property Agent'), ('CUSTOMER_ADMIN', 'Corporate'), ('PROPERTY_ADMIN', 'Property Manager')], max_length=32),
        ),
    ]
