# Generated by Django 2.2.13 on 2020-12-06 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0181_platformswitchactivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformswitchactivity',
            options={'verbose_name_plural': 'Platform Switch Activities'},
        ),
    ]
