# Generated by Django 2.2.13 on 2020-12-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0182_auto_20201206_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproperty',
            name='agent_chat_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='agent_chat_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
