# Generated by Django 2.2.13 on 2020-12-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0183_auto_20201207_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatprospect',
            name='unloaded_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
