# Generated by Django 2.2.13 on 2020-12-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0184_chatprospect_unloaded_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproperty',
            name='is_calls_scored_today',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_calls_scored_today',
            field=models.BooleanField(default=False),
        ),
    ]
