# Generated by Django 2.2.13 on 2020-12-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0186_auto_20201216_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypolicy',
            name='monthly_utility_bill',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='requirements_to_hold_unit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
