# Generated by Django 2.2.13 on 2021-01-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0188_auto_20210105_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
