# Generated by Django 2.2.13 on 2021-01-17 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0190_historicaluser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='has_access_to_up_platform',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_access_to_up_platform',
        ),
        migrations.DeleteModel(
            name='PlatformSwitchActivity',
        ),
    ]
