# Generated by Django 2.2.13 on 2021-01-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0191_auto_20210117_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasedefault',
            name='late_charges_after_days',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leasedefault',
            name='storage_unit_late_fee_after_days',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypolicy',
            name='longest_lease_term',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypolicy',
            name='max_one_bedroom_occupants',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypolicy',
            name='max_pets_for_four_leaseholders',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypolicy',
            name='max_pets_for_one_leaseholder',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypolicy',
            name='max_pets_for_three_leaseholders',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypolicy',
            name='max_pets_for_two_leaseholders',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypolicy',
            name='max_pets_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypolicy',
            name='max_studio_occupants',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypolicy',
            name='max_three_bedrooms_occupants',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypolicy',
            name='max_two_bedrooms_occupants',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypolicy',
            name='max_vehicles_for_four_leaseholders',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypolicy',
            name='max_vehicles_for_one_bedroom',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypolicy',
            name='max_vehicles_for_one_leaseholder',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypolicy',
            name='max_vehicles_for_studio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypolicy',
            name='max_vehicles_for_three_bedrooms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypolicy',
            name='max_vehicles_for_three_leaseholders',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypolicy',
            name='max_vehicles_for_two_bedrooms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypolicy',
            name='max_vehicles_for_two_leaseholders',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypolicy',
            name='notice_to_vacate_month_to_month_days',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypolicy',
            name='notice_to_vacate_prior_days',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypolicy',
            name='shortest_lease_term',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
