# Generated by Django 2.2.13 on 2021-01-20 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0192_auto_20210118_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPolices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('basic_qualification_requirements', models.TextField(blank=True, null=True)),
                ('accept_section_eight', models.BooleanField(default=False)),
                ('section_eight_disclaimer', models.TextField(blank=True, null=True)),
                ('accept_unemployment_as_income', models.BooleanField(default=True)),
                ('unemployment_income_disclaimer', models.TextField(blank=True, null=True)),
                ('accept_applicant_without_ssn', models.BooleanField(default=True)),
                ('ssn_disclaimer', models.TextField(blank=True, null=True)),
                ('accept_applicant_with_misdemeanors_or_felonies', models.BooleanField(default=True)),
                ('misdemeanor_or_felony_disclaimer', models.TextField(blank=True, null=True)),
                ('is_hard_inquiry_on_credit_report', models.BooleanField(default=True)),
                ('screening_process_time', models.CharField(blank=True, choices=[('24_HOURS', '24 hours'), ('48_HOURS', '48 hours'), ('72_HOURS', '72 hours')], max_length=32, null=True)),
                ('is_valet_waste_service_optional', models.BooleanField(default=False)),
                ('is_alley_waste_service_optional', models.BooleanField(default=False)),
                ('application_refund_policy', models.TextField(blank=True, null=True)),
                ('package_policy', models.TextField(blank=True, null=True)),
                ('lease_break_policy', models.TextField(blank=True, null=True)),
                ('transfer_policy', models.TextField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_polices', to='api.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
