# Generated by Django 2.2.13 on 2021-01-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0194_auto_20210122_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_activity',
        ),
    ]
