# Generated by Django 2.2.13 on 2021-02-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0195_auto_20210126_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproperty',
            name='block_spam_calls_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='block_spam_calls_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
