# Generated by Django 2.2.13 on 2021-02-10 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0196_auto_20210204_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='HobbesConversations',
            fields=[
            ],
            options={
                'ordering': ['-date'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.chatconversation',),
        ),
        migrations.RemoveField(
            model_name='chatconversation',
            name='bot_response_state',
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='question',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='api.ChatConversation'),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='question_result',
            field=models.CharField(blank=True, choices=[('ANSWERED', 'Answered'), ('REPHRASED', 'Rephrased'), ('FAILED', 'Failed'), ('NO_DATA', 'No data')], max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='HobbesCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_succeed', models.BooleanField(default=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='hobbes_check_export/')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hobbes_checks', to='api.Property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
