# Generated by Django 2.2.13 on 2021-02-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0197_auto_20210210_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproperty',
            name='hobbes_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='hobbes_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
