# Generated by Django 2.2.13 on 2021-02-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0198_auto_20210210_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproperty',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
