# Generated by Django 2.2.13 on 2021-02-12 14:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0199_auto_20210210_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='sources',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('LOST', 'Lost'), ('DELETED', 'Deleted'), ('TEST', 'Test')], default='ACTIVE', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('LOST', 'Lost'), ('DELETED', 'Deleted'), ('TEST', 'Test')], default='ACTIVE', max_length=16, null=True),
        ),
    ]
