# Generated by Django 2.2.13 on 2021-02-12 15:16

from django.db import migrations


def migrate_relationship_types(apps, *args, **kwargs):
    Report = apps.get_model('api', 'Report')
    for report in Report.objects.all():
        report.emails_new = report.emails
        report.notes_new = report.notes
        report.tasks_new = report.tasks
        report.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0201_auto_20210212_1516'),
    ]

    operations = [
        migrations.RunPython(migrate_relationship_types),
    ]
