# Generated by Django 2.2.13 on 2021-02-12 15:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0202_migrate_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='report',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='report',
            name='tasks',
        ),
    ]
