# Generated by Django 2.2.13 on 2021-02-12 15:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0203_auto_20210212_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='emails_new',
            new_name='emails',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='notes_new',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='tasks_new',
            new_name='tasks',
        ),
    ]
