# Generated by Django 2.2.13 on 2021-02-20 03:04

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0204_auto_20210212_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='lost_leads',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='prospectsource',
            name='spends',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='agents_call_score',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='amenities_score',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='call_score',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='closing_score',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='emails',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='facetime_tours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='facetime_tours_leases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='followups_24_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='followups_2_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='followups_48_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='followups_more_48_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='followups_number',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='guided_virtual_tours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='guided_virtual_tours_leases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='in_person_tours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='in_person_tours_leases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='introduction_score',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='lead_response_time_business',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='lead_response_time_non_business',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='leads',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='leases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='notes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='overall_score',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='qualifying_score',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='sign_lease_time',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='sources',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='tasks',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='tours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='virtual_tours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='virtual_tours_leases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, null=True, size=None),
        ),
    ]
