# Generated by Django 2.2.13 on 2021-02-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0205_auto_20210220_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypolices',
            name='about_customer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
