# Generated by Django 2.2.13 on 2021-02-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0206_companypolices_about_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertypolicy',
            name='apartment_hold_expiration',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manually released'), ('24_HOURS', '24 hours'), ('48_HOURS', '48 hours'), ('72_HOURS', '72 hours'), ('WEEK', '1 week'), ('TWO_WEEKS', '2 weeks')], max_length=32, null=True),
        ),
    ]
