# Generated by Django 2.2.13 on 2021-03-02 15:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0207_auto_20210224_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproperty',
            name='bedroom_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ONE_BEDROOM', '1 bedroom'), ('TWO_BEDROOM', '2 bedroom'), ('THREE_BEDROOM', '3 bedroom'), ('FOUR_BEDROOM', '4 bedroom')], max_length=32), default=['ONE_BEDROOM', 'TWO_BEDROOM', 'THREE_BEDROOM'], size=None),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='is_booking_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bedroom_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ONE_BEDROOM', '1 bedroom'), ('TWO_BEDROOM', '2 bedroom'), ('THREE_BEDROOM', '3 bedroom'), ('FOUR_BEDROOM', '4 bedroom')], max_length=32), default=['ONE_BEDROOM', 'TWO_BEDROOM', 'THREE_BEDROOM'], size=None),
        ),
        migrations.AddField(
            model_name='property',
            name='is_booking_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='tour_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('VIRTUAL_TOUR', 'Virtual Tour'), ('GUIDED_VIRTUAL_TOUR', 'Guided Virtual Tour'), ('IN_PERSON', 'In-Person Tour'), ('FACETIME', 'Facetime Tour'), ('SELF_GUIDED_TOUR', 'Self-Guided Tour')], max_length=32), blank=True, default=['VIRTUAL_TOUR', 'GUIDED_VIRTUAL_TOUR', 'FACETIME', 'IN_PERSON', 'SELF_GUIDED_TOUR'], size=None),
        ),
        migrations.AlterField(
            model_name='property',
            name='tour_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('VIRTUAL_TOUR', 'Virtual Tour'), ('GUIDED_VIRTUAL_TOUR', 'Guided Virtual Tour'), ('IN_PERSON', 'In-Person Tour'), ('FACETIME', 'Facetime Tour'), ('SELF_GUIDED_TOUR', 'Self-Guided Tour')], max_length=32), blank=True, default=['VIRTUAL_TOUR', 'GUIDED_VIRTUAL_TOUR', 'FACETIME', 'IN_PERSON', 'SELF_GUIDED_TOUR'], size=None),
        ),
    ]
