# Generated by Django 2.2.13 on 2021-03-12 18:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0208_auto_20210302_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatconversation',
            name='question',
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='hobbes_answer',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
