# Generated by Django 2.2.13 on 2021-03-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0209_auto_20210312_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallead',
            name='last_reactivated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_reactivated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
