# Generated by Django 2.2.13 on 2021-03-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0210_auto_20210322_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='callscoringquestion',
            name='is_not_omitting',
            field=models.BooleanField(default=False),
        ),
    ]
