# Generated by Django 2.2.13 on 2021-03-24 09:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0211_callscoringquestion_is_not_omitting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='followups_24_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=[0, 0], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='followups_2_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=[0, 0], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='followups_48_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=[0, 0], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='followups_more_48_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=[0, 0], null=True, size=None),
        ),
    ]
