# Generated by Django 2.2.13 on 2021-04-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0213_auto_20210331_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproperty',
            name='is_text_me_feature_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_text_me_feature_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
