# Generated by Django 2.2.13 on 2021-04-21 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0214_auto_20210409_0115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HobbesCheck',
        ),
    ]
