# Generated by Django 2.2.13 on 2021-04-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0215_delete_hobbescheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
