# Generated by Django 2.2.19 on 2021-05-12 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0216_auto_20210422_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realpageemployee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_page_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resmanemployee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='res_man_employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
