# Generated by Django 2.2.19 on 2021-05-14 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0217_auto_20210512_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallead',
            name='last_stage',
            field=models.CharField(blank=True, choices=[('INQUIRY', 'Inquiry'), ('CONTACT_MADE', 'Contact made'), ('TOUR_SET', 'Tour set'), ('TOUR_COMPLETED', 'Tour completed'), ('WAITLIST', 'Waitlist'), ('APPLICATION_PENDING', 'Application pending'), ('APPLICATION_COMPLETE', 'Application complete')], default='INQUIRY', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_stage',
            field=models.CharField(blank=True, choices=[('INQUIRY', 'Inquiry'), ('CONTACT_MADE', 'Contact made'), ('TOUR_SET', 'Tour set'), ('TOUR_COMPLETED', 'Tour completed'), ('WAITLIST', 'Waitlist'), ('APPLICATION_PENDING', 'Application pending'), ('APPLICATION_COMPLETE', 'Application complete')], default='INQUIRY', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('LEAD_CREATED', 'Lead created'), ('TASK_CREATED', 'Task created'), ('NOTE_CREATED', 'Note created'), ('EMAIL_CREATED', 'Email created'), ('LEAD_UPDATED', 'Lead updated'), ('TASK_COMPLETED', 'Task completed'), ('TOUR_CREATED', 'Tour created'), ('TOUR_UPDATED', 'Tour updated'), ('TOUR_CANCELLED', 'Tour cancelled'), ('LEAD_UPDATED', 'Lead updated'), ('LEAD_SHARED', 'Lead shared'), ('LEAD_CHAT_HOBBES', 'Chat with Hobbes'), ('SMS_CREATED', 'SMS created')], max_length=16),
        ),
        migrations.AlterField(
            model_name='event',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('NO_SHOW', 'No Show')], default='OPEN', max_length=16),
        ),
    ]
