# Generated by Django 2.2.19 on 2021-05-25 08:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0219_demoevent_demotour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproperty',
            name='bedroom_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('STUDIO', 'Studio'), ('ONE_BEDROOM', '1 bedroom'), ('TWO_BEDROOM', '2 bedroom'), ('THREE_BEDROOM', '3 bedroom'), ('FOUR_BEDROOM', '4 bedroom')], max_length=32), default=['ONE_BEDROOM', 'TWO_BEDROOM', 'THREE_BEDROOM'], size=None),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('STUDIO', 'Studio'), ('ONE_BEDROOM', '1 bedroom'), ('TWO_BEDROOM', '2 bedroom'), ('THREE_BEDROOM', '3 bedroom'), ('FOUR_BEDROOM', '4 bedroom')], max_length=32), default=['ONE_BEDROOM', 'TWO_BEDROOM', 'THREE_BEDROOM'], size=None),
        ),
    ]
