# Generated by Django 2.2.19 on 2021-06-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0220_auto_20210525_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrequest',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
