# Generated by Django 2.2.19 on 2021-06-03 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0221_agentrequest_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveAgentRequestState',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.agentrequest',),
        ),
        migrations.AlterField(
            model_name='chatprospect',
            name='conversion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_prospects', to='api.Conversion'),
        ),
        migrations.AlterField(
            model_name='chatprospect',
            name='guest_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_prospects_for_guest', to='api.Lead'),
        ),
        migrations.AlterField(
            model_name='chatprospect',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_prospects', to='api.Lead'),
        ),
    ]
