# Generated by Django 2.2.19 on 2021-06-04 14:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0222_auto_20210603_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatprospect',
            name='tour_scheduling_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='last_property',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Property'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_with_last_property', to='api.Property'),
        ),
        migrations.CreateModel(
            name='ChatTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('text', models.TextField(blank=True, max_length=8192, null=True)),
                ('variables', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128), blank=True, null=True, size=None)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats_templates', to='api.Property')),
            ],
            options={
                'unique_together': {('property', 'name')},
            },
        ),
    ]
