# Generated by Django 2.2.19 on 2021-06-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0223_auto_20210604_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('LEAD_CREATED', 'Lead created'), ('TASK_CREATED', 'Task created'), ('NOTE_CREATED', 'Note created'), ('EMAIL_CREATED', 'Email created'), ('LEAD_UPDATED', 'Lead updated'), ('TASK_COMPLETED', 'Task completed'), ('TOUR_CREATED', 'Tour created'), ('TOUR_UPDATED', 'Tour updated'), ('TOUR_CANCELLED', 'Tour cancelled'), ('LEAD_SHARED', 'Lead shared'), ('LEAD_CHAT_HOBBES', 'Chat with Hobbes'), ('SMS_CREATED', 'SMS created'), ('TASK_UPDATED', 'Task updated'), ('TASK_DELETED', 'Task deleted'), ('LEAD_MERGED', 'Lead merged'), ('ROOMMATE_CREATED', 'Roommate created')], max_length=16),
        ),
    ]
