# Generated by Django 2.2.19 on 2021-06-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0224_auto_20210614_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypolicy',
            name='apartment_ceiling_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='resident_parking_type',
            field=models.CharField(blank=True, choices=[('COVERED_PARKING', 'Assigned, covered parking'), ('UNCOVERED_PARKING', 'Assigned, uncovered parking'), ('BOTH_PARKING', 'Assigned, covered and uncovered parking')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='smoking_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='smoking_policy_disclaimer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
