# Generated by Django 2.2.19 on 2021-06-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0225_auto_20210614_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('LEAD_CREATED', 'Lead created'), ('TASK_CREATED', 'Task created'), ('NOTE_CREATED', 'Note created'), ('EMAIL_CREATED', 'Email created'), ('LEAD_UPDATED', 'Lead updated'), ('TASK_COMPLETED', 'Task completed'), ('TOUR_CREATED', 'Tour created'), ('TOUR_UPDATED', 'Tour updated'), ('TOUR_CANCELLED', 'Tour cancelled'), ('LEAD_SHARED', 'Lead shared'), ('LEAD_CHAT_HOBBES', 'Chat with Hobbes'), ('SMS_CREATED', 'SMS created'), ('TASK_UPDATED', 'Task updated'), ('TASK_DELETED', 'Task deleted'), ('LEAD_MERGED', 'Lead merged'), ('ROOMMATE_CREATED', 'Roommate created'), ('ROOMMATE_UPDATED', 'Roommate updated'), ('ROOMMATE_DELETED', 'Roommate deleted')], max_length=16),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='type',
            field=models.CharField(choices=[('AGENT', 'Agent message'), ('BOT', 'Bot message'), ('PROSPECT', 'Prospect message'), ('JOINED', 'Agent joined'), ('AGENT_REQUEST', 'Agent request'), ('GREETING', 'Greeting message'), ('DATA_CAPTURE', 'Data capture element'), ('TEMPLATE', 'Template')], default='BOT', max_length=32),
        ),
    ]
