# Generated by Django 2.2.19 on 2021-06-22 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0226_auto_20210622_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallead',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='secondary_phone_number',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator('\\d+')]),
        ),
        migrations.AddField(
            model_name='lead',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='secondary_phone_number',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator('\\d+')]),
        ),
    ]
