# Generated by Django 2.2.19 on 2021-07-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0229_auto_20210707_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallead',
            name='is_deleted_by_merging',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_deleted_by_merging',
            field=models.BooleanField(default=False),
        ),
    ]
