# Generated by Django 2.2.19 on 2021-07-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0230_auto_20210708_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
    ]
