# Generated by Django 2.2.19 on 2021-08-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0231_note_is_auto_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailattachment',
            name='attachment',
            field=models.FileField(upload_to='email_attachments'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('NO_SHOW', 'No Show'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=16),
        ),
    ]
