# Generated by Django 2.2.19 on 2021-08-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0233_auto_20210807_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='logo',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='property_logo/'),
        ),
    ]
