# Generated by Django 2.2.19 on 2021-09-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0235_auto_20210812_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='ILSEmailAddress',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.property',),
        ),
        migrations.AddField(
            model_name='leasedefault',
            name='document_update_change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leasedefault',
            name='electric_company_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='leasedefault',
            name='electric_company_phone_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='leasedefault',
            name='electric_company_website',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='leasedefault',
            name='gas_company_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='leasedefault',
            name='gas_company_phone_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='leasedefault',
            name='gas_company_website',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='leasedefault',
            name='pet_non_refundable_deposit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
