# Generated by Django 2.2.19 on 2021-09-30 04:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0236_auto_20210928_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertypolicy',
            name='is_offer_month_to_month',
        ),
        migrations.RemoveField(
            model_name='propertypolicy',
            name='longest_lease_term',
        ),
        migrations.RemoveField(
            model_name='propertypolicy',
            name='shortest_lease_term',
        ),
        migrations.CreateModel(
            name='DurationPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('shortest_lease_term', models.IntegerField(blank=True, null=True)),
                ('longest_lease_term', models.IntegerField(blank=True, null=True)),
                ('is_offer_month_to_month', models.BooleanField(default=True)),
                ('base_rent', models.IntegerField(blank=True, null=True)),
                ('base_rent_type', models.CharField(choices=[('PLUS', 'Plus'), ('NO_PREMIUM', 'No premium'), ('MINUS', 'Minus')], default='NO_PREMIUM', max_length=32)),
                ('base_rent_measurement', models.CharField(choices=[('PERCENT', 'Percent'), ('FIXED', 'Fixed')], default='FIXED', max_length=32)),
                ('pricing_term', models.CharField(choices=[('DYNAMIC', 'Dynamic'), ('MANUAL', 'Manual')], default='DYNAMIC', max_length=32)),
                ('avg_turnover_time', models.IntegerField(blank=True, null=True)),
                ('avg_turnover_costs', models.IntegerField(blank=True, null=True)),
                ('is_offer_discounts', models.BooleanField(default=False)),
                ('term_premiums', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duration_pricing', to='api.Property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
