# Generated by Django 2.2.19 on 2021-10-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0237_auto_20210930_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leasedefault',
            name='parking_rent',
        ),
        migrations.RemoveField(
            model_name='propertypolicy',
            name='guest_parking_allowed',
        ),
        migrations.AddField(
            model_name='leasedefault',
            name='facilities_late_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leasedefault',
            name='fob_replacement_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leasedefault',
            name='management_fax_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='leasedefault',
            name='no_lease_first_violation_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leasedefault',
            name='no_lease_subsequent_violation_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leasedefault',
            name='pet_waste_first_violation_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leasedefault',
            name='pet_waste_subsequent_violation_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leasedefault',
            name='towing_company_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='leasedefault',
            name='towing_company_phone_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='leasedefault',
            name='towing_company_website',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='leasedefault',
            name='trash_container_replacement_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leasedefault',
            name='trash_left_out_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leasedefault',
            name='unlock_after_hours_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='club_house_alarm_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='club_house_hours_24_hr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='club_house_hours_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='club_house_hours_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='community_quiet_hours_24_hr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='community_quiet_hours_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='community_quiet_hours_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='fitness_center_hours_24_hr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='fitness_center_hours_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='fitness_center_hours_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='fitness_center_key_deposit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='garage_door_opener_replacement_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='garage_door_reprogramming_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='guest_parking_is_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='guest_parking_type',
            field=models.CharField(blank=True, choices=[('ANY_UNASSIGNED_SPACE', 'In any unassigned space'), ('SPACES_MARKED_FOR_GUEST_OR_VISITORS', 'In spaces marked for guest or visitors'), ('GUEST_VEHICLE_DISPLAY_GUEST_PASS', 'When the guest vehicle is displaying a guest pass')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='moving_hours_24_hr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='moving_hours_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='moving_hours_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='overnight_guest_stay_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='parking_id_replacement_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='parking_permit_rent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='parking_rent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='pest_control_service_day',
            field=models.CharField(blank=True, choices=[('MONDAYS', 'mondays'), ('TUESDAYS', 'tuesdays'), ('WEDNESDAYS', 'wednesdays'), ('THURSDAYS', 'thursdays'), ('FRIDAYS', 'fridays'), ('SATURDAYS', 'saturdays'), ('SUNDAYS', 'sundays')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='pool_hours_24_hr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='pool_hours_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertypolicy',
            name='pool_hours_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
