# Generated by Django 3.2.8 on 2021-11-07 02:08

import backend.api.models.property
import backend.api.models.report
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0239_auto_20211025_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demoevent',
            name='participants',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='bedroom_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('STUDIO', 'Studio'), ('ONE_BEDROOM', '1 bedroom'), ('TWO_BEDROOM', '2 bedroom'), ('THREE_BEDROOM', '3 bedroom'), ('FOUR_BEDROOM', '4 bedroom')], max_length=32), default=backend.api.models.property.default_bedroom_types, size=None),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='tour_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('VIRTUAL_TOUR', 'Virtual Tour'), ('GUIDED_VIRTUAL_TOUR', 'Guided Virtual Tour'), ('IN_PERSON', 'In-Person Tour'), ('FACETIME', 'Facetime Tour'), ('SELF_GUIDED_TOUR', 'Self-Guided Tour')], max_length=32), blank=True, default=backend.api.models.property.default_tour_types, size=None),
        ),
        migrations.AlterField(
            model_name='lead',
            name='floor_plan',
            field=models.ManyToManyField(blank=True, related_name='leads', to='api.FloorPlan'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='leads', to='api.Unit'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('STUDIO', 'Studio'), ('ONE_BEDROOM', '1 bedroom'), ('TWO_BEDROOM', '2 bedroom'), ('THREE_BEDROOM', '3 bedroom'), ('FOUR_BEDROOM', '4 bedroom')], max_length=32), default=backend.api.models.property.default_bedroom_types, size=None),
        ),
        migrations.AlterField(
            model_name='property',
            name='nylas_selected_calendars',
            field=models.ManyToManyField(blank=True, related_name='properties', to='api.Calendar'),
        ),
        migrations.AlterField(
            model_name='property',
            name='nylas_selected_labels',
            field=models.ManyToManyField(blank=True, related_name='properties', to='api.EmailLabel'),
        ),
        migrations.AlterField(
            model_name='property',
            name='tour_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('VIRTUAL_TOUR', 'Virtual Tour'), ('GUIDED_VIRTUAL_TOUR', 'Guided Virtual Tour'), ('IN_PERSON', 'In-Person Tour'), ('FACETIME', 'Facetime Tour'), ('SELF_GUIDED_TOUR', 'Self-Guided Tour')], max_length=32), blank=True, default=backend.api.models.property.default_tour_types, size=None),
        ),
        migrations.AlterField(
            model_name='prospectsource',
            name='spends',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='followups_24_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=backend.api.models.report.default_followups, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='followups_2_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=backend.api.models.report.default_followups, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='followups_48_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=backend.api.models.report.default_followups, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='followups_more_48_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=backend.api.models.report.default_followups, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='scoredcall',
            name='omitted_questions',
            field=models.ManyToManyField(blank=True, related_name='omitted_scored_calls', to='api.CallScoringQuestion'),
        ),
        migrations.AlterField(
            model_name='scoredcall',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='scored_calls', to='api.CallScoringQuestion'),
        ),
        migrations.AlterField(
            model_name='task',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='tours', to='api.Unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='lease_dates',
            field=models.JSONField(default=list),
        ),
    ]
