# Generated by Django 3.2.8 on 2021-11-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0240_auto_20211107_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='acquisition_channels_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='conversion_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='demographics_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='devices_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='seo_score_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='site_visitor_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='source_behavior_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
