version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/crm
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_python_dependencies
      timeout: 6000
      runas: root
    - location: scripts/migrate
      timeout: 6000
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: ubuntu
  AfterAllowTraffic:
    - location: scripts/reallocate_ips
      timeout: 300
      runas: root
  AfterBlockTraffic:
    - location: scripts/stop_celery_worker
      timeout: 300
      runas: root
