# Generated by Django 2.2.19 on 2021-09-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0003_auto_20210428_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='dollar_value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='lease_duration',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='promotion',
            name='lease_duration_modifier',
            field=models.CharField(choices=[('Exactly', 'Exactly'), ('More than', 'More than'), ('Less than', 'Less than'), ('All months', 'All months')], default='More than', max_length=20),
        ),
    ]
