# Generated by Django 2.2.19 on 2021-10-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0004_auto_20210930_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='dollar_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
