# Generated by Django 3.2.8 on 2021-11-08 19:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0005_auto_20211009_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagedata',
            name='values',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
        ),
    ]
