export default {
  BASE: '/',
  LOGIN: '/login',
  PASSWORD_RESET: '/password-reset/:token',
  SEND_PASSWORD_RESET_EMAIL: '/password-reset-email',
  LEADS: {
    VIEW: '/:propertyHyphens/leads',
    OVERVIEW: '/:propertyHyphens/leads/:id',
    NOTES: '/:propertyHyphens/leads/:id/notes',
    CALLS: '/:propertyHyphens/leads/:id/calls',
    EMAILS: '/:propertyHyphens/leads/:id/emails',
    CHATS: '/:propertyHyphens/leads/:id/chats',
    SMS: '/:propertyHyphens/leads/:id/sms',
  },
  TASKS: '/:propertyHyphens/tasks',
  SETTINGS: {
    VIEW: '/:propertyHyphens/settings',
    ASSIGN_LEAD_OWNERS: '/:propertyHyphens/settings/assign_lead_owners',

    LIST_TEMPLATE: '/:propertyHyphens/settings/template/list',
    NEW_TEMPLATE: '/:propertyHyphens/settings/template/new',
    EDIT_TEMPLATE: '/:propertyHyphens/settings/template/edit/:id',

    CHAT_LIST_TEMPLATE: '/:propertyHyphens/settings/chat_template/list',

    EMAIL_SYNC: '/:propertyHyphens/settings/email_sync',
    PAID_SOURCES: '/:propertyHyphens/settings/paid_sources',
    COMPETITORS: '/:propertyHyphens/settings/competitors',
    BUSINESS_HOURS: '/:propertyHyphens/settings/business_hours',
    TOUR_OPTIONS: '/:propertyHyphens/settings/tour_options',
    LEASE_DEFAULTS: '/:propertyHyphens/settings/lease_defaults',
    PROPERTY_POLICIES: '/:propertyHyphens/settings/property_polices',
    RENTABLE_ITEMS: '/:propertyHyphens/settings/rentable_items',
    DURATION_PRICING: '/:propertyHyphens/settings/duration_pricing',

    LIST_PAID_SOURCE_BUDGET: '/:propertyHyphens/settings/paid_source_budget/list',
    NEW_PAID_SOURCE_BUDGET: '/:propertyHyphens/settings/paid_source_budget/new',
    EDIT_PAID_SOURCE_BUDGET: '/:propertyHyphens/settings/paid_source_budget/edit',

    LIST_RENT_SURVEY: '/:propertyHyphens/settings/rent_survey/list',
    NEW_RENT_SURVEY: '/:propertyHyphens/settings/rent_survey/new',
    EDIT_RENT_SURVEY: '/:propertyHyphens/settings/rent_survey/edit',
  },
  PROFILE: '/profile',
  NYLAS_INTEGRATION: '/nylas_integrate',
  FOLLOWUPS: {
    VIEW: '/:propertyHyphens/followups',
    DETAILS: '/:propertyHyphens/followups/:id',
  },
  BULK_EMAIL: '/:propertyHyphens/bulk_email',
  REPORTS: {
    BASIC: '/:propertyHyphens/reports',
    ADVANCED: '/:propertyHyphens/advanced-reports',
  },
  CALLS: '/:propertyHyphens/calls',
  CHATS: {
    OVERVIEW: '/:propertyHyphens/chats',
    EVALUATION: '/:propertyHyphens/chats/evaluate/:id',
    REPORT: '/:propertyHyphens/chats/report/:id',
  },
  MULTI_CHAT: '/:propertyHyphens/multi_chat',
  SITE_CONTENT: {
    HOME: '/:propertyHyphens/site-contents',
    GALLERY: '/:propertyHyphens/site-gallery',
    FLOOR_PLANS: '/:propertyHyphens/site-floor',
    AMENITIES: '/:propertyHyphens/site-amenities',
    NEIGHBORHOOD: '/:propertyHyphens/site-neighborhood',
    VIRTUAL_TOUR: '/:propertyHyphens/site-virtual',
    CONTACT: '/:propertyHyphens/site-contact',
    FOOTER: '/:propertyHyphens/site-footer',
    DESIGN: '/:propertyHyphens/site-design',
    MISC: '/:propertyHyphens/site-misc',
    PROMOTIONS: '/:propertyHyphens/site-promotions',
  },

  MANAGE_USERS: '/:propertyHyphens?/users',
  MANAGE_CUSTOMERS: '/:propertyHyphens?/customers',
  MANAGE_CLIENTS: '/:propertyHyphens?/clients',
  MANAGE_PROPERTIES: '/:propertyHyphens?/properties',
  HOBBES_SETTINGS: '/:propertyHyphens/hobbes',

  COMPETE: {
    HOME: '/:propertyHyphens/compete',
    PROPERTY_REPORT: '/:propertyHyphens/compete/property-report/:propertyId',
    SUBMARKET_REPORT: '/:propertyHyphens/compete/submarket-report/:submarketId',
    MARKET_REPORT: '/:propertyHyphens/compete/market-report/:marketId',
    COMPARISON_REPORT: '/:propertyHyphens/compete/comparison',
    COMPARISON_REPORT_ID: '/:propertyHyphens/compete/comparison/report/:comparisonId',
    ALERTS_SUBSCRIPTIONS: '/:propertyHyphens/compete/alerts',
    ALERTS_SUMMARY: '/:propertyHyphens/compete/alerts/:summaryId',
    ALERTS_LOG: '/:propertyHyphens/compete/alerts/:summaryId/:logId',
  },
};
