# Generated by Django 2.2.13 on 2021-04-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='is_supported',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='name_in_hobbes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='amenitycategory',
            name='is_supported',
            field=models.BooleanField(default=True),
        ),
    ]
