# Generated by Django 2.2.19 on 2021-05-10 01:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbes', '0002_auto_20210428_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbesautotestquestion',
            name='entities',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
