# Generated by Django 2.2.19 on 2021-09-01 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0235_auto_20210812_1113'),
        ('hobbes', '0003_auto_20210510_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('session_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=32)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_conversations_evaluation_report', to='api.Property')),
            ],
            options={
                'ordering': ['session_date'],
            },
        ),
        migrations.CreateModel(
            name='ChatReportConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_chats', to='api.ChatProspect')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='hobbes.ChatReport')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ChatReportMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('CORRECT', 'Correct'), ('INCORRECT', 'Incorrect')], max_length=32, null=True)),
                ('support_status', models.CharField(choices=[('SUPPORTED', 'Supported'), ('NOT_SUPPORTED', 'Not supported')], max_length=32, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_messages', to='hobbes.ChatReportConversation')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_messages', to='api.ChatConversation')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
