# Generated by Django 3.2.8 on 2021-11-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbes', '0004_chatreport_chatreportconversation_chatreportmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbesautotestquestion',
            name='entities',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
