export default {
  LEAD_CREATED: 'ri-user-add-line',
  TASK_CREATED: 'ri-task-line',
  TOUR_CREATED: 'ri-calendar-event-line',
  NOTE_CREATED: 'ri-sticky-note-line',
  NOTE_UPDATED: 'ri-sticky-note-line',
  NOTE_DELETED: 'ri-delete-bin-5-line',
  EMAIL_CREATED: 'ri-mail-send-line',
  TASK_COMPLETED: 'ri-user-follow-line',
  TOUR_COMPLETED: 'ri-user-follow-line',
  TOUR_CANCELLED: 'ri-user-unfollow-line',
  TOUR_UPDATED: 'ri-calendar-event-line',
  SMS_CREATED: 'ri-message-2-line',
  LEAD_CHAT_HOBBES: 'ri-rocket-2-fill',
  LEAD_UPDATED: 'ri-contacts-line',
  LEAD_SHARED: 'ri-share-line',
  EMAIL: 'ri-mail-line',
  CALL: 'ri-phone-line',
  SMS: 'ri-chat-3-line',
  CHATS: 'ri-rocket-fill',
  NOTE: 'ri-sticky-note-line',
  TASK_UPDATED: 'ri-restart-line',
  TASK_DELETED: 'ri-delete-bin-5-line',
  LEAD_MERGED: 'ri-group-line',
  ROOMMATE_CREATED: 'ri-group-fill',
  ROOMMATE_UPDATED: 'ri-user-follow-fill',
  ROOMMATE_DELETED: 'ri-user-unfollow-fill',
};
