export default {
  LEAD_CREATED: 'New Lead',
  TASK_CREATED: 'Added New Task',
  TOUR_CREATED: 'Added New Tour',
  NOTE_CREATED: 'Internal Note',
  NOTE_UPDATED: 'Note Updated',
  NOTE_DELETED: 'Note Deleted',
  EMAIL_CREATED: 'Email Sent',
  TASK_COMPLETED: 'Task Completed',
  TOUR_COMPLETED: 'Tour Completed',
  TOUR_CANCELLED: 'Tour Canceled',
  TOUR_UPDATED: 'Tour Updated',
  SMS_CREATED: 'SMS',
  LEAD_CHAT_HOBBES: 'Chat with Hobbes',
  LEAD_UPDATED: 'Updated Lead',
  LEAD_SHARED: 'Shared Lead',
  LEAD_MERGED: 'Merged Leads',
  TASK_UPDATED: 'Task Updated',
  TASK_DELETED: 'Task Deleted',
  ROOMMATE_CREATED: 'Added New Roommate',
  ROOMMATE_UPDATED: 'Roommate Updated',
  ROOMMATE_DELETED: 'Roommate Deleted',
};
