export default {
  LEAD_FILED_CHOICES: {
    status: {
      ACTIVE: { title: 'Active', text: 'Active leads impact reporting metrics, surface on the \n Pipeline page and all associated tasks are active for \n completion.', hide: false },
      CLOSED: { title: 'Leased', text: 'Leased leads impact reporting metrics and all \n associated lease related tasks are marked completed. ', hide: false },
      LOST: { title: 'Lost', text: 'Lost leads impact reporting metrics, do not surface as active on the Pipeline page and all associated tasks are deleted.', hide: false },
      TEST: { title: 'Test', text: 'Test leads do not impact reporting, do not surface on the \n Pipeline page and associated tasks are not listed as a \n part of the Tasks page or daily team tasking.', hide: false },
      DELETED: { title: 'Deleted', text: 'Previously deleted options', hide: true },
    },
    stage: {
      INQUIRY: 'Inquiry',
      CONTACT_MADE: 'Contact made',
      TOUR_SET: 'Tour set',
      TOUR_COMPLETED: 'Tour completed',
      WAITLIST: 'Waitlist',
      APPLICATION_PENDING: 'Application pending',
      APPLICATION_COMPLETE: 'Application complete',
    },
    contactMethod: {
      EMAIL: 'Email',
      PHONE: 'Phone',
      TEXT: 'Text',
    },
    contactTime: {
      MORNING: 'Morning',
      AFTERNOON: 'Afternoon',
      EVENING: 'Evening',
    },
    origin: {
      WEB: 'Web',
      MOBILE: 'Mobile',
      PHONE: 'Phone',
      WALK_IN: 'Walk In',
      UNKNOWN: 'Unknown',
    },
    movingReason: {
      EMPLOYMENT: 'Employment',
      FAMILY: 'Family',
      OTHER: 'Other',
    },
    petType: {
      DOG: 'Dog',
      CAT: 'Cat',
      BIRD: 'Bird',
    },
    washerDryerMethod: {
      IN_UNIT: 'In Unit',
      HOOK_UP_ONLY: 'Hook up only',
      ON_PREMISE: 'On premise',
      NONE: 'None',
    },
    pmsSyncStatus: {
      SUCCESS: 'Success',
      FAILURE: 'Failure',
      NOT_STARTED: 'Not started yet',
    },
  },
  TASK_FILED_CHOICES: {
    type: {
      FIRST_FOLLOWUP: '1st Follow-up',
      SECOND_FOLLOWUP: '2nd Follow-up',
      THIRD_FOLLOWUP: '3rd Follow-up',
      FINAL_FOLLOWUP: 'Final Follow-up',
      FUTURE_DATE_FOLLOWUP: 'Future Date Follow-up',
      CHECK_APP: 'Check for Application',
      CHECK_DOCS: 'Check for Documents',
      PRICE_AVAILABILITY: 'Send New Price/Availability',
      TOUR: 'Schedule Tour',
      VIRTUAL_TOUR: 'Schedule Virtual Tour',
      IN_PERSON: 'In-Person Tour',
      SELF_GUIDED_TOUR: 'Self-Guided Tour',
      GUIDED_VIRTUAL_TOUR: 'Guided Virtual Tour',
      FACETIME: 'Facetime Tour',
    },
  },
  PROPERTY_POLICY_FILED_CHOICES: {
    apartmentHoldExpiration: {
      MANUAL: 'Manually released',
      '24_HOURS': '24 hours',
      '48_HOURS': '48 hours',
      '72_HOURS': '72 hours',
      WEEK: '1 week',
      TWO_WEEKS: '2 weeks',
    },
    residentParkingType: {
      COVERED_PARKING: 'Assigned, covered parking',
      UNCOVERED_PARKING: 'Assigned, uncovered parking',
      BOTH_PARKING: 'Assigned, covered and uncovered parking',
    },
    guestParkingTypes: {
      ANY_UNASSIGNED_SPACE: 'In any unassigned space',
      SPACES_MARKED_FOR_GUEST_OR_VISITORS: 'In spaces marked for guest or visitors',
      GUEST_VEHICLE_DISPLAY_GUEST_PASS: 'When the guest vehicle is displaying a guest pass',
    },
    utilities: {
      ELECTRIC: 'electric',
      WATER: 'water',
      TRASH: 'trash',
      GAS: 'gas',
      SEWER: 'sewer',
      RENTERS_INSURANCE: 'renters insurance',
      VALET_TRASH_SERVICE: 'valet trash service',
    },
    pestControlServiceDay: {
      MONDAYS: 'Mondays',
      TUESDAYS: 'Tuesdays',
      WEDNESDAYS: 'Wednesdays',
      THURSDAYS: 'Thursdays',
      FRIDAYS: 'Fridays',
      SATURDAYS: 'Saturdays',
      SUNDAYS: 'Sundays',
    },
    paymentForms: {
      PERSONAL_CHECK: 'Personal Check',
      CASHIER_CHECK: 'Cashier\'s Check',
      ELECTRONIC_CHECK: 'Electronic Check',
      CREDIT_CARD: 'Credit Card',
      DEBIT_CARD: 'Debit Card',
      ONLINE_PAYMENT: 'Online Payment',
      MONEY_ORDER: 'Money Order',
    },
  },
};
