#!/bin/bash
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
apt-get install -y software-properties-common
add-apt-repository ppa:deadsnakes/ppa
apt-get install -y nodejs
apt-get install -y python3.9
apt-get install -y python3-pip
apt-get install -y build-essential
apt-get install -y libssl-dev
apt-get install -y libffi-dev
apt-get install -y python-dev
apt-get install -y python3.9-venv
apt-get install -y nginx
apt-get install -y npm
npm install -g pm2

rm -rf /home/ubuntu/crm
