# Generated by Django 2.2.13 on 2021-04-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0002_auto_20210406_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='phone_number',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
