# Generated by Django 2.2.13 on 2021-04-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0003_auto_20210406_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='is_valuable',
            field=models.BooleanField(default=True),
        ),
    ]
