# Generated by Django 2.2.13 on 2021-04-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0004_history_is_valuable'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_lease_up',
            field=models.BooleanField(default=False),
        ),
    ]
