# Generated by Django 2.2.19 on 2021-05-29 02:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0005_property_is_lease_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='condition_unit_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('STUDIO', 'Studio'), ('ONE_BEDROOM', '1 bedroom'), ('TWO_BEDROOM', '2 bedroom'), ('THREE_BEDROOM', '3 bedroom'), ('FOUR_BEDROOM', '4 bedroom'), ('FIVE_BEDROOM', '5 bedroom'), ('COMBINED', 'Combined')], max_length=32, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='alertlog',
            name='condition_unit_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('STUDIO', 'Studio'), ('ONE_BEDROOM', '1 bedroom'), ('TWO_BEDROOM', '2 bedroom'), ('THREE_BEDROOM', '3 bedroom'), ('FOUR_BEDROOM', '4 bedroom'), ('FIVE_BEDROOM', '5 bedroom'), ('COMBINED', 'Combined')], max_length=32, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='property',
            name='completed_units_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='mt_submarket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mt_properties', to='compete.Submarket'),
        ),
        migrations.AddField(
            model_name='submarket',
            name='is_mt_exclusive_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submarket',
            name='is_mtr_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submarket',
            name='mtr_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mtr_submarkets', to='compete.Submarket'),
        ),
    ]
