# Generated by Django 2.2.19 on 2021-06-07 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0006_auto_20210529_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='condition_unit_type',
        ),
        migrations.RemoveField(
            model_name='alertlog',
            name='condition_unit_type',
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(blank=True, choices=[('GARDEN_STYLE', 'Garden Style'), ('SFR', 'SFR'), ('MID_RISE', 'Mid-Rise'), ('HIGH_RISE', 'High-Rise')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='on_market',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unitrentreport',
            name='blended_rent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UnitSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start_listing_date', models.DateField()),
                ('end_listing_date', models.DateField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_sessions', to='compete.Property')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_sessions', to='compete.Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
