# Generated by Django 2.2.19 on 2021-06-08 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0007_auto_20210607_0106'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('property', 'number')},
        ),
    ]
