# Generated by Django 2.2.19 on 2021-06-18 01:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0008_auto_20210608_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='condition_unit_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('STUDIO', 'Studio'), ('ONE_BEDROOM', '1 bedroom'), ('TWO_BEDROOM', '2 bedroom'), ('THREE_BEDROOM', '3 bedroom'), ('FOUR_BEDROOM', '4 bedroom'), ('FIVE_BEDROOM', '5 bedroom'), ('COMBINED', 'Combined')], max_length=32, null=True), blank=True, default=list, size=None),
        ),
    ]
