name: Test Pre-Commit
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install "pre-commit==2.15.0"
      - name: Test with pre-commit
        run: |
          pre-commit run --all-files
